server:
  jetty:
    threads:
      acceptors: 4
      selectors: 8
  port: 8005
  servlet:
    context-path: /

spring:
  profiles:
    #引用application-common.yml文件
    include: common
  application:
    name: hxds-oes
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3307/hxds?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: abc123456
      initial-size: 4
      max-active: 8
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 6
    host: localhost
    port: 6379
    password: abc123456
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  cloud:
    inetutils:
      #子系统注册到Nacos上的IP地址
      preferred-networks: 127.0.0.1
    nacos:
      #配置子系统在Web管理页面上的注册信息
      config:
        group: DEFAULT_GROUP
        file-extension: yaml
        server-addr: 127.0.0.1:8848
        prefix: ${spring.application.name}
        namespace: hxds
      #配置子系统在Nacos上的注册信息
      discovery:
        namespace: hxds
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        heart-beat-interval: 1000
        heart-beat-timeout: 1000
        group: DEFAULT_GROUP
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB


springdoc:
  api-docs:
    enabled: true
    path: /doc-api.html
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: on

tx-lcn:
  client:
    #连接TM节点
    manager-address: 127.0.0.1:8070

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 300000